spring:
  datasource:
    url: jdbc:postgresql://localhost:38121/member
    username: lgcms
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 38122
      database: 15
server:
  port: 38109